[package]
name = "ruffle_core"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
linkme = { version = "0.3", optional = true }
byteorder = "1.4"
bitstream-io = "1.6.0"
flate2 = "1.0.25"
fnv = "1.0.7"
gc-arena = { workspace = true }
generational-arena = "0.2.8"
indexmap = "1.9.2"
tracing = "0.1.37"
ruffle_render = { path = "../render" }
ruffle_video = { path = "../video" }
ruffle_macros = { path = "macros" }
ruffle_wstr = { path = "../wstr" }
swf = { path = "../swf" }
bitflags = "2.0.0"
smallvec = { version = "1.10.0", features = ["union"] }
num-traits = "0.2"
num-derive = "0.3"
quick-xml = { git = "https://github.com/ruffle-rs/quick-xml", rev = "8496365ec1412eb5ba5de350937b6bce352fa0ba" }
downcast-rs = "1.2.0"
url = "2.3.1"
weak-table = "0.3.2"
percent-encoding = "2.2.0"
thiserror = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
instant = "0.1"
encoding_rs = "0.8.32"
rand = { version = "0.8.5", features = ["std", "small_rng"], default-features = false }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
nellymoser-rs = { git = "https://github.com/ruffle-rs/nellymoser", rev = "4a33521c29a918950df8ae9fe07e527ac65553f5", optional = true }
regress = "0.5"
flash-lso = { git = "https://github.com/ruffle-rs/rust-flash-lso", rev = "8376453eddddbe701031a091c0eed94068fa5649" }
lzma-rs = {version = "0.3.0", optional = true }
dasp = { git = "https://github.com/RustAudio/dasp", rev = "f05a703", features = ["interpolate", "interpolate-linear", "signal"], optional = true }
symphonia = { version = "0.5.2", default-features = false, features = ["mp3"], optional = true }
enumset = "1.0.12"
static_assertions = "1.1.0"
rustversion = "1.0.12"
bytemuck = "1.13.1"
clap = { version = "4.1.8", features = ["derive"], optional=true }
realfft = "3.2.0"
once_cell = "1.8.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies.futures]
version = "0.3.26"

[target.'cfg(target_family = "wasm")'.dependencies.wasm-bindgen-futures]
version = "0.4.34"

[features]
default = []
lzma = ["lzma-rs", "swf/lzma"]
wasm-bindgen = [ "instant/wasm-bindgen" ]
avm_debug = []
deterministic = []
timeline_debug = []
mp3 = ["symphonia"]
nellymoser = ["nellymoser-rs"]
audio = ["dasp"]
known_stubs = ["linkme"]
default_compatibility_rules = []

[build-dependencies]
build_playerglobal = { path = "build_playerglobal" }
